version: 2.1
orbs:
  trivy-orb: fifteen5/trivy-orb@1.0.0

jobs:

  build_and_push:
    docker:
      - image: cimg/python:3.12
    working_directory: ~/app
    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Build the Image 
          command: | 
            docker build -t cci .
            docker tag cci $ECR_REGISTRY/cci:$(git rev-parse --short HEAD)
          working_directory: ~/app

      - run:
          name: Check AWS CLI Installation
          command: |
             sudo apt -y -qq update
             sudo apt install -y awscli
             sudo apt install -y python3-pip
             sudo pip3 install --upgrade awscli
      - run:
          name: Configure AWS Environment
          command: |
            echo "export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" >> $BASH_ENV
            echo "export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY" >> $BASH_ENV
            echo "export AWS_REGION=${{ context.aws-context.$AWS_REGION }}" >> $BASH_ENV
            source $BASH_ENV  

      - run:
          name: Push to ECR
          command: |
            eval $(aws ecr get-login --no-include-email --region $AWS_REGION)
            docker push $ECR_REGISTRY/cci:$(git rev-parse --short HEAD)

      - trivy-orb/scan:
          args: '--no-progress --exit-code 1 image $ECR_REGISTRY/cci:$(git rev-parse --short HEAD)'

workflows:
  version: 2
  build:
    jobs:
      - build_and_push:
          filters:
            branches:
              only: 
                - main
                - dummy
