version: 2.1

workflows:
  test-build:
    jobs:
      - build
      - test

jobs:
  test:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install --upgrade pip
            pip install -r requirements.txt 
        # Install the Python dependencies listed in 'requirements.txt'

      - run:
          name: Python Test
          command: pytest
        # Run Python tests using pytest

  build:
    docker:
      - image: docker:20.10.11
        environment:
          DOCKER_HOST: tcp://localhost:2375
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.11
          docker_layer_caching: true
        # Set up Docker using the Docker executor

      - run:
          name: Build Docker image
          command: |
            docker build -t hello-world .
        # Build the Docker image using the Dockerfile

      - run:
          name: Push Docker image
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker tag hello-world:latest "$DOCKERHUB_USERNAME/hello-world:latest"
            docker push "$DOCKERHUB_USERNAME/hello-world:latest"
        # Tag and push the Docker image to a Docker registry (e.g., Docker Hub)
