version: 2.1

jobs:

  build_and_push:
    docker:
      - image: cimg/python:3.11.4
    working_directory: ~/app
    steps:
      - checkout

      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true

      - run:
          name: Build the Image 
          command: docker build -t 324221743401.dkr.ecr.eu-west-3.amazonaws.com/cci .
          working_directory: ~/app

      - run:
          name: Check AWS CLI Installation
          command: |
             sudo apt -y -qq update
             sudo apt install -y awscli
      - run:
          name: Configure AWS Environment
          command: |
            echo "export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" >> $BASH_ENV
            echo "export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY" >> $BASH_ENV
            source $BASH_ENV  
      - run:
          name: Push to ECR
          command: |
            eval $(aws ecr get-login --no-include-email --region eu-west-1) > login.sh
            docker push 324221743401.dkr.ecr.eu-west-3.amazonaws.com/cci:latest

workflows:
  build:
    jobs:
      - build_and_push

