version: 2.1

jobs:
  build:
    name: Build and Test
    docker:
      - image: cimg/python:3.11.4
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: Show current branch
          command: echo $CIRCLE_BRANCH
      - run:
          name: Build the Image 
          command: docker build -t flask-app .
workflows:
  version: 2
  build:
    jobs:
      - build
