version: 2.1

workflows:
  test-build:
    jobs:
      - build
      - test

jobs:
  test:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install --upgrade pip
            pip install -r requirements.txt 
        # Install the Python dependencies listed in 'requirements.txt'

      - run:
          name: Python Test
          command: pytest
        # Run Python tests using pytest

  build:
    machine:
      enabled: true
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.11
        # Setup remote Docker to build the Docker image

      - run:
          name: Build Docker image
          command: |
            docker build -t hello-world .
        # Build the Docker image using the Dockerfile

      - run:
          name: Push Docker image
          command: |
            docker tag hello-world:latest your-dockerhub-username/hello-world:latest
            docker login -u your-dockerhub-username -p your-dockerhub-password
            docker push your-dockerhub-username/hello-world:latest
        # Tag and push the Docker image to a Docker registry (e.g., Docker Hub)

        
