version: 2.1

workflows:
  test-build:
    jobs:
      - test
      # Uncomment or remove the following line if you want to include the 'build' job in the workflow.
      # - build

jobs:
  test:
    docker:
      - image: cimg/python:3.11.4
    steps:
      - checkout
      - run: Install dependencies 
          command: pip install -r requirements.txt
        # Install the Python dependencies listed in 'requirements.txt'

      - run: Python Test
          command: pytest
        # Run Python tests using pytest
