version: 2.1

job:
  build:
    docker:
      - image: cimg/python:3.11.4
    working_dirertoty: ~/app
    steps:
      -checkout
      - run:
        name: Show current branch
          command: echo $(CURRENT_BRANCH)
      - run:
        name: Build the Image 
          command: docker-build -t flask-app .
    filters:
      branches:
        only:
          - build

workflows:
  build
    jobs:
      - build