version: 2.1

workflows:
  test-build:
    jobs:
      - test
      - build

jobs:
  test:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install --upgrade pip
            pip install -r .circleci/requirements/requirements.txt
            pip install pytest  # Install pytest package
        # Install the Python dependencies listed in '.circleci/requirements/requirements.txt'

      - run:
          name: Python Test
          command: pytest
        # Run Python tests using pytest

  build:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - setup_remote_docker:  # This enables Docker-in-Docker (DinD) in CircleCI
          version: 20.10.7
      - run:
          name: Build Docker image
          command: docker build -t helloworld .
        # Build the Docker image for your application with the tag "helloworld"
        # The '.' at the end specifies the build context as the current directory

      - run:
          name: Push Docker image
          command: docker push helloworld
        # Optionally, push the Docker image to a container registry like Docker Hub
