version: 2.1

orbs:
  aws-cli: circleci/aws-cli@4.0.0

jobs:
  configure_role_arn:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          profile_name: default
      - aws-cli/role_arn_setup:
          profile_name: new-profile
          role_arn: arn:aws:iam::324221743401:user/terraform-user
          source_profile: default
      - run: >-
          aws sts assume-role --role_arn
          "arn:aws:iam::324221743401:user/terraform-user" --role_session_name
          AWSCLI-Session

  build_and_push:
    docker:
      - image: cimg/python:3.11.4
    working_directory: ~/app
    steps:
      - checkout

      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true

      - run:
          name: Build the Image 
          command: docker build -t 324221743401.dkr.ecr.eu-west-3.amazonaws.com/cci:v.01 .
          working_directory: ~/app
      - run:
          name: Configure AWS Environment
          command: |
            echo 'export AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION' >> $BASH_ENV
            echo 'export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID' >> $BASH_ENV
            echo 'export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY' >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Check AWS CLI Installation
          command: aws --version
      - run:
          name: Authenticate AWS CLI
          command: aws ecr get-login-password --region $AWS_DEFAULT_REGION | sh

      - run:
          name: Push to ECR
          command: |
            eval $(aws ecr get-login | sed 's|https://||')
            docker push 324221743401.dkr.ecr.eu-west-3.amazonaws.com/cci
workflows:
  build:
    jobs:
      - configure_role_arn
      - build_and_push

