version: 2.1

executors:
  default:
    docker:
      - image: cimg/python:3.9

workflows:
  test-build:
    jobs:
      - build
      - test

jobs:
  test:
    executor: default
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install --upgrade pip
            pip install -r requirements.txt 
        # Install the Python dependencies listed in 'requirements.txt'

      - run:
          name: Python Test
          command: pytest
        # Run Python tests using pytest

  build:
    executor: default
    steps:
      - checkout
      - run:
          name: Build Docker image
          command: docker build -t hello-world .
