version: 2.1

jobs:

  build_and_push:
    docker:
      - image: cimg/python:3.11.4
    working_directory: ~/app
    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Build the Image 
          command: | 
            docker build -t cci .
            docker tag cci:latest 324221743401.dkr.ecr.eu-west-3.amazonaws.com/cci:latest
          working_directory: ~/app

      - run:
          name: Check AWS CLI Installation
          command: |
             sudo apt -y -qq update
             sudo apt install -y awscli
             sudo apt install -y python3-pip
             sudo pip3 install --upgrade awscli
      - run:
          name: Configure AWS Environment
          command: |
            echo "export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" >> $BASH_ENV
            echo "export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY" >> $BASH_ENV
            source $BASH_ENV  

      - run:
          name: Push to ECR
          command: |
            $(aws ecr get-login-password --region eu-west-3 | docker login --username AWS --password-stdin 324221743401.dkr.ecr.eu-west-3.amazonaws.com)
            docker push 324221743401.dkr.ecr.eu-west-3.amazonaws.com/cci:latest


workflows:
  build:
    jobs:
      - build_and_push
