version: 2.1

workflows:
  test-build:
    jobs:
      - test
      - build

jobs:
  test:
    docker:
      - image: cimg/python:3.11.4
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install --upgrade pip
            pip install -r requirements.txt
            pip install pytest  # Install pytest package
        # Install the Python dependencies listed in '.circleci/requirements/requirements.txt'

      - run:
          name: Python Test
          command: pytest
        # Run Python tests using pytest
      - run:
          name: Python Test
          command: |
            export PATH=$PATH:/path/to/pytest/bin
            pytest

  build:
    docker:
      - image: cimg/python:3.11.4
    steps:
      - checkout
      # Add the steps for building your application here
      # For example, you can run commands to compile assets, build binaries, etc.
