version: 2.1

jobs:
  build_and_push:
    docker:
      - image: cimg/python:3.11.4
    working_directory: app
    steps:
      - checkout
      - run:
          name: Show current branch
          command: echo $CIRCLE_BRANCH
      - run:
          name: Build the Image 
          command: docker build -t 324221743401.dkr.ecr.eu-west-3.amazonaws.com/flask-image .
          working_directory: app

      - setup_remote_docker:
          version: 20.10.14
      - run:
          name: Configure AWS Environment
          command: |
            echo 'export AWS_DEFAULT_REGION=your_region' >> $BASH_ENV
            echo 'export AWS_ACCESS_KEY_ID=your_access_key' >> $BASH_ENV
            echo 'export AWS_SECRET_ACCESS_KEY=your_secret_key' >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Push Image to ECR
          command: |
            eval $(aws ecr get-login --no-include-email --region your_region)
            docker push 324221743401.dkr.ecr.eu-west-3.amazonaws.com/flask-image:${CIRCLE_SHA1}

workflows:
  version: 2
  build:
    jobs:
      - build_and_push
