version: 2.1

workflows:
  test-build:
    jobs:
      - test
      - build  # Add the 'build' job here
      
jobs:
  test:
    docker:
      - image: cimg/python:3.11.4
    steps:
      - checkout
      - run:
          name: Install dependencies 
          command: pip install -r requirements.txt
        # Install the Python dependencies listed in 'requirements.txt'

      - run:
          name: Python Test
          command: pytest
        # Run Python tests using pytest

  build:  # New 'build' job definition
    docker:
      - image: cimg/python:3.11.4
    steps:
      - checkout
      # Add the steps for building your application here
      # For example, you can run commands to compile assets, build binaries, etc.
